name: macos-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          ./CI/install-dependencies-macos.sh

      - name: Build OBS
        run: |
          ./CI/install-build-obs-macos.sh

      - name: Build obs-ios-camera-source
        run: |
          ./CI/build-macos.sh

      - name: Install release signing certificates
        run: |
          echo TODO

      - name: Package obs-ios-camera-source
        env:
          RELEASE_MODE: false
          # CODE_SIGNING_IDENTITY: $(secrets.macOS.codeSigningIdentity)
          # INSTALLER_SIGNING_IDENTITY: $(secrets.macOS.installerSigningIdentity)
          # AC_USERNAME: $(secrets.macOS.notarization.username)
          # AC_PASSWORD: $(secrets.macOS.notarization.password)
          # AC_PROVIDER_SHORTNAME: $(secrets.macOS.notarization.providerShortName)
        run: |
          ./CI/package-macos.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: build-macos
          path: release
